[tool.poetry]
name = "estoque-medicamento-cdc"
version = "0.3.0"
description = "Pipeline CDC em tempo real com PostgreSQL, Debezium, Kafka, Redis e Streamlit"
authors = ["David Vaz"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
kafka-python = "^2.0.2"
redis = "^5.0"
streamlit = "^1.40"
plotly = "^5.24"
pandas = "^2.2"
requests = "^2.32"
python-dotenv = "^1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
